### ISSUE TITLE
Error when gradle  version 2.6.2

### ISSUE THREAD

**Issue by ngocdtph03070** [vvorld/getid-android-sdk#10]
When I sync the lib version and I get error 

`FAILURE: Build completed with 7 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find ru.terrakok.cicerone:cicerone:5.0.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/ru/terrakok/cicerone/cicerone/5.0.0/cicerone-5.0.0.pom
       - https://repo.maven.apache.org/maven2/ru/terrakok/cicerone/cicerone/5.0.0/cicerone-5.0.0.pom
       - https://storage.googleapis.com/download.flutter.io/ru/terrakok/cicerone/cicerone/5.0.0/cicerone-5.0.0.pom
     Required by:
         project :app > ee.getid:getidlib:2.6.2
   > Could not find com.reginald:editspinner:1.0.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/reginald/editspinner/1.0.0/editspinner-1.0.0.pom
       - https://repo.maven.apache.org/maven2/com/reginald/editspinner/1.0.0/editspinner-1.0.0.pom
       - https://storage.googleapis.com/download.flutter.io/com/reginald/editspinner/1.0.0/editspinner-1.0.0.pom
     Required by:
         project :app > ee.getid:getidlib:2.6.2
   > Could not find com.agrawalsuneet.androidlibs:dotsloader:1.4.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/agrawalsuneet/androidlibs/dotsloader/1.4.1/dotsloader-1.4.1.pom
       - https://repo.maven.apache.org/maven2/com/agrawalsuneet/androidlibs/dotsloader/1.4.1/dotsloader-1.4.1.pom
       - https://storage.googleapis.com/download.flutter.io/com/agrawalsuneet/androidlibs/dotsloader/1.4.1/dotsloader-1.4.1.pom
     Required by:
         project :app > ee.getid:getidlib:2.6.2
   > Could not find com.github.MasayukiSuda:Mp4Composer-android:v0.4.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/MasayukiSuda/Mp4Composer-android/v0.4.0/Mp4Composer-android-v0.4.0.pom
       - https://repo.maven.apache.org/maven2/com/github/MasayukiSuda/Mp4Composer-android/v0.4.0/Mp4Composer-android-v0.4.0.pom
       - https://storage.googleapis.com/download.flutter.io/com/github/MasayukiSuda/Mp4Composer-android/v0.4.0/Mp4Composer-android-v0.4.0.pom
     Required by:
         project :app > ee.getid:getidlib:2.6.2
   > Could not find com.otaliastudios:cameraview:2.7.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/otaliastudios/cameraview/2.7.0/cameraview-2.7.0.pom
       - https://repo.maven.apache.org/maven2/com/otaliastudios/cameraview/2.7.0/cameraview-2.7.0.pom
       - https://storage.googleapis.com/download.flutter.io/com/otaliastudios/cameraview/2.7.0/cameraview-2.7.0.pom
     Required by:
         project :app > ee.getid:getidlib:2.6.2

**Comment by Kiriakovd88** [comment]
The issue with dependencies was fixed on April 15, please let me know if you have more questions.
