### ISSUE TITLE
Problem with com.github.corouteam:GlideToVectorYou:v2.0.0

### ISSUE THREAD

**Issue by september669** [vvorld/getid-android-sdk#11]
Failed to build project due to outdated com.github.corouteam:GlideToVectorYou:v2.0.0
This dependency needs to be replaced with com.github.2coffees1team:GlideToVectorYou:v2.0.0

**Comment by asolntsev** [comment]
Need this issue to be fixed! Our application doesn't build anymore. :( 

@september669 I also could not use `com.github.2coffees1team:GlideToVectorYou:v2.0.0` dependency.

**Comment by Kiriakovd88** [comment]
The issues were fixed on January 05, please use the 2.7.7 release version or higher.
