### ISSUE TITLE
Support for React native 

### ISSUE THREAD

**Issue by theDevSoham** [vvorld/getid-android-sdk#13]
Hi, I'm having a problem with this library in react native.

## The problem
So I'm currently using RN v0.71.3. After providing the `implementation 'ee.getid:getidlib:2.7.7'` statement into `android/app/build.gradle`, it gives an error mentioning some dependencies not found which are used by the `getidlib`.

## The error
~~~ error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find ru.terrakok.cicerone:cicerone:5.0.0.
     Required by:
         project :app > ee.getid:getidlib:2.7.7
   > Could not find com.reginald:editspinner:1.0.0.
     Required by:
         project :app > ee.getid:getidlib:2.7.7
   > Could not find com.agrawalsuneet.androidlibs:dotsloader:1.4.1.
     Required by:
         project :app > ee.getid:getidlib:2.7.7
   > Could not find com.otaliastudios:cameraview:2.7.0.
     Required by:
         project :app > ee.getid:getidlib:2.7.7 
~~~

From what I understand the following libraries couldn't be fetched
<ul>
<li>ru.terrakok.cicerone:cicerone:5.0.0.</li>
<li>com.reginald:editspinner:1.0.0</li>
<li>com.agrawalsuneet.androidlibs:dotsloader:1.4.1</li>
<li>com.otaliastudios:cameraview:2.7.0</li>
</ul>

## Things I tried
So tried searching for the following libraries and I found all of these in the Maven Central repository system. Still somehow it's not loading in the project. Can someone help me regarding this matter?

**Comment by Kiriakovd88** [comment]
The issue with the packages was resolved on Jan 9, 2023
