### ISSUE TITLE
java.lang.IllegalArgumentException: x + width must be <= bitmap.width()

### ISSUE THREAD

**Issue by vadikk** [vvorld/getid-android-sdk#8]
I try to test getID at tablet but get exception when try to take a photo. This bug was reproduced at Galaxy Tab A7 and emulator Nexus 10, but at phone - everything OK. Please fix this ASAP.

![getid_error](https://user-images.githubusercontent.com/25104323/135283992-bd420d59-9c46-4b5b-94fe-80ae53e200b8.png)

**Comment by wacumov** [comment]
@vadikk Thanks for the bug report. We'll fix it in the next release.

**Comment by wacumov** [comment]
@vadikk We've fixed this issue in version 2.3.2.
