### ISSUE TITLE
apiUrl param seems to ignore everything after /

### ISSUE THREAD

**Issue by TheFaithOne** [vvorld/getid-android-sdk#9]
For internal automated tests purposes we have a mock service that is located at https://example.com/mockId/. However when the flow starts it always sends https://example.com/sdk/v2/configuration?name=flow omitting whatever path I put after .com/. It works fine for my iOS colleague so I wanted to ask if this is intended behavior and if so, what's the reasoning behind it?

Real API URL that we have from the dashboard seems to be working fine, but I would assume only because it doesn't have any additional paths.

SDK version 2.6.0

**Comment by anyefremov** [comment]
This issue is related to url auto resolving by Retrofit library that we are using internally.
As a solution for current sdk version you can pass your url without trailing '/' ('https://example.com/mockId').
We will add support for both cases (with and without a trailing '/') in future versions of sdk. 
Thanks for pointing this issue.

**Comment by TheFaithOne** [comment]
Great, thanks for your prompt response. I have a feeling that SDK crashes if I don't supply trailing "/" with IllegalArgumentException, however I'm not 100% sure if this was 2.6.0 or 2.5.1. I'll give it a quick try and edit this response.

Cheers!

**Comment by anyefremov** [comment]
I just double checked and indeed there is a problem with missing leading
'/', so we will make a hot fix in a short term

**Comment by TheFaithOne** [comment]
Howdy, is there some kind of ETA for the fix/hotfix that would at least allow passing url without trailing "/"?
Thanks.

**Comment by anyefremov** [comment]
Hi! Hopefully new version with fix will be released till end of this week

**Comment by TheFaithOne** [comment]
Hiya, I can confirm that the issue has been resolved in 2.6.2 and paths are present as expected. The issue with missing trailing "/" also appears to be resolved. Thank you. However I've found some other weird behavior that I would like to ask about. As it isn't necessarily connected to this issue, I'll close this one and open a new one for discussion.
